language: cpp

os: osx

before_install:
  - brew update
  - brew update
  - brew install apr apr-util
  - brew install --build-from-source netpbm
  - brew doctor
  - brew config


script:
  - ls -la /usr/local/lib/libnetpbm*
  - ls -la /usr/local/Cellar/netpbm/10.76_1/lib/
  - find ~/Library/Caches/Homebrew/netpbm--svn/lib
  - find /usr/local/Cellar/netpbm/10.76_1
